# Site settings
title: Actor Notes
email: don@actornotes.com
description: > 
  Collaborative acting thoughts. Read journal entries from other actors and contribute your own. Let's all have an epiphany together!
baseurl: "/jekyll.actornotes.com"
url: "http://happycollision.github.io"
twitter_username: actornotes

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['smart']

permalink: pretty

exclude:
  - .bowerrc
  - .gitignore
  - bower.json
